MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = bone.020 bone.025 bone.030 bone.035 bone.040 bone.045 bone.050 bone.055 \
 bone.060 bone.065 bone.070 bone.075 bone.080 bone.085 bone.090 bone.095
PACKAGE = ghost
