MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = artifact.txt cost_adj.txt ego_item.txt flavor.txt hints.txt limits.txt monster.txt names.txt object.txt p_class.txt p_hist.txt p_race.txt set_item.txt shop_own.txt spell.txt terrain.txt themed.txt vault.txt
PACKAGE = edit

