MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = artifact.txt cost_adj.txt ego_item.txt flavor.txt limits.txt monster.txt object.txt p_class.txt p_hist.txt p_race.txt set_item.txt shop_own.txt terrain.txt themed.txt vault.txt
PACKAGE = ${PACKAGE_NAME}/edit

