/*
 * File: list-effects.h
 * Purpose: List of effect types
 */

/*
 * "rating" is the power rating for an item activation, as a damage-per-blow
 * equivalent (x2). These ratings are used in the calculation of the power (and
 * therefore cost) of an item which has the effect as an activation, but NOT
 * for other items (e.g. potions, scrolls). Hence the use of INIHIBIT_POWER.
 */

/*     name            aim?   rating	short description	*/
EFFECT(XXX,            FALSE,  0,	NULL)
EFFECT(POISON1,        FALSE,  0,	"poisons you for 12-20 turns")  
EFFECT(POISON2,        FALSE,  0,	"poisons you for 20-30 turns")
EFFECT(BLIND1,         FALSE,  0,	"blinds you for 1d200+200 turns")
EFFECT(BLIND2,         FALSE,  0,	"blinds you for 1d100+100 turns")
EFFECT(SCARE,          FALSE,  0,	"induces fear in you for 1d10+10 turns")
EFFECT(CONFUSE1,       FALSE,  0,	"confuses you for 1d10+10 turns")
EFFECT(CONFUSE2,       FALSE,  0,	"confuses you for 1d20+15 turns")
EFFECT(HALLUC,         FALSE,  0,	"causes you to hallucinate for 1d250 + 250 turns")
EFFECT(PARALYSE,       FALSE,  0,	"induces paralysis for 1d10+10 turns")
EFFECT(WEAKNESS,       FALSE,  0,	"reduces your strength with damage 6d6")
EFFECT(SICKNESS,       FALSE,  0,	"reduces your constitution with damage 6d6")
EFFECT(STUPIDITY,      FALSE,  0,	"reduces your intelligence with damage 8d8")
EFFECT(NAIVETY,        FALSE,  0,	"reduces your wisdom with damage 8d8")
EFFECT(UNHEALTH,       FALSE,  0,	"reduces your constitution with damage 10d10")
EFFECT(DISEASE,        FALSE,  0,	"reduces your strength with damage 10d10")
EFFECT(DETONATIONS,    FALSE,  0,	"inflicts 50d20 points of damage, severe cuts, and stunning")
EFFECT(DEATH,          FALSE,  0,	"reduces your hitpoints to zero")
EFFECT(SLOWNESS,       FALSE,  0,	"slows you for 1d25+15 turns")
EFFECT(SALT_WATER,     FALSE,  0,	"induces vomiting and paralysis for 4 turns, resulting in severe hunger but also curing poison")
EFFECT(SLEEP,          FALSE,  0,	"induces paralysis for 1d4+4 turns")
EFFECT(LOSE_MEMORIES,  FALSE,  0,	"drains a quarter of your experience")
EFFECT(RUINATION,      FALSE,  0,	"inflicts 5d10 points of damage and decreases all your stats")
EFFECT(DEC_STR,        FALSE,  0,	"reduces your strength")
EFFECT(DEC_INT,        FALSE,  0,	"reduces your intelligence")
EFFECT(DEC_WIS,        FALSE,  0,	"reduces your wisdom")
EFFECT(DEC_DEX,        FALSE,  0,	"reduces your dexterity")
EFFECT(DEC_CON,        FALSE,  0,	"reduces your constitution")
EFFECT(DEC_CHR,        FALSE,  0,	"reduces your charisma")
EFFECT(AGGRAVATE,      FALSE,  0,	"awakens all nearby sleeping monsters")
EFFECT(CURSE_ARMOR,    FALSE,  0,	"curses your currently worn body armor")
EFFECT(CURSE_WEAPON,   FALSE,  0,	"curses your currently wielded melee weapon")
EFFECT(SUMMON3,        FALSE,  0,	"summons monsters at the current dungeon level")
EFFECT(SUMMON_UNDEAD,  FALSE,  0,	"summons undead monsters at the current dungeon level")
EFFECT(TRAP_CREATION,  FALSE,  0,	"creates traps surrounding you")
EFFECT(DARKNESS,       FALSE,  0,	"darkens the nearby area and blinds you for 1d5+3 turns") 
EFFECT(SLOWNESS,       FALSE,  0,	"slows you for 1d30+15 turns")
EFFECT(HASTE_MONSTERS, FALSE,  0,	"hastes all monsters within line of sight")
EFFECT(SUMMON4,        FALSE,  0,	"summons monsters at the current dungeon level")
EFFECT(HEAL_MONSTER,   TRUE,   0,	"heals a single monster 4d6 hit points")
EFFECT(HASTE_MONSTER,  TRUE,   0,	"hastes a single monster")
EFFECT(CLONE_MONSTER,  TRUE,   0,	"hastes, heals, and magically duplicates a single monster")
EFFECT(ROUSE_LEVEL,    FALSE,  0,	"awakens and hastes every monster on the level")
EFFECT(CURE_POISON,    FALSE,  1,	"neutralizes poison")
EFFECT(CURE_BLINDNESS, FALSE,  4,	"cures blindness")
EFFECT(CURE_PARANOIA,  FALSE,  2,	"removes your fear")
EFFECT(CURE_CONFUSION, FALSE,  4,	"cures confusion")
EFFECT(CURE_SMALL,     FALSE,  3,	"restores 4d8 hitpoints")
EFFECT(RES_STR,        FALSE,  10,	"restores your strength")
EFFECT(RES_INT,        FALSE,  8,	"restores your intelligence")
EFFECT(RES_WIS,        FALSE,  8,	"restores your wisdom")
EFFECT(RES_DEX,        FALSE,  9,	"restores your dexterity")
EFFECT(RES_CON,        FALSE,  10,	"restores your constitution")
EFFECT(RES_CHR,        FALSE,  4,	"restores your charisma")
EFFECT(RESTORING,      FALSE,  15,	"restores all your stats")
EFFECT(ATHELAS,        FALSE,  15,	"heals you of poison, stunning, cuts and the Black Breath")
EFFECT(BEORNING,       FALSE,  3,	"restores 5d8 hitpoints")
EFFECT(FOOD_GOOD,      FALSE,  0,	NULL)
EFFECT(WAYBREAD,       FALSE,  5,	"restores 5d10 hit points and halves poison")
EFFECT(DRINK_GOOD,     FALSE,  0,	NULL) 
EFFECT(CURE_LIGHT,     FALSE,  3,	"restores 2d10 hitpoints, heals a little cut damage and cures blindness")
EFFECT(CURE_SERIOUS,   FALSE,  6,	"restores 4d10 hitpoints, heals some cut damage, and cures blindness and confusion")
EFFECT(CURE_CRITICAL,  FALSE,  10,	"restores 6d10 hitpoints, heals considerable cut damage, reduces poisoning by over a half, and cures stunning, blindness, and confusion")
EFFECT(HEALING1,       FALSE,  11,	"restores 300 hitpoints and cures cuts and stunning")
EFFECT(HEALING2,       FALSE,  12,	"restores 500 hitpoints and cures cuts and stunning")
EFFECT(HEALING3,       FALSE,  12,	"restores 300 hitpoints, considerably reduces poison and heals cut damage, stunning, blindness, and confusion")
EFFECT(HEALING4,       FALSE,  18,	"restores 600 hit points, heals cut damage, and cures stunning, poisoning, blindness, confusion and the Black Breath")
EFFECT(LIFE,           FALSE,  22,	"restores 2000 hit points, restores experience and stats, heals cut damage, and cures stunning, poison, blindness, confusion, hallucination and the Black Breath")
EFFECT(INFRAVISION,    FALSE,  4,	"extends your infravision by 50 feet for 1d100+100 turns"L)
EFFECT(SEE_INVIS,      FALSE,  5,	"allows you to see invisible things for 1d12+12 turns")
EFFECT(SLOW_POISON,    FALSE,  1,	"halves poisoning")
EFFECT(SPEED1,         FALSE,  9,	"hastens you for 1d20+15 turns")
EFFECT(RES_HEAT_COLD,  FALSE,  7,	"grants temporary resistance to fire and cold for 1d30+20 turns")
EFFECT(RES_ACID_ELEC,  FALSE,  7,	"grants temporary resistance to acid and electricity for 1d30+20 turns")
EFFECT(RESIST_ALL,     FALSE,  10,	"grants temporary resistance to acid, electricity, fire, cold and poison for 1d25+15 turns")
EFFECT(HEROISM,        FALSE,  7,	"restores 10 hit points, removes fear and grants you resistance to fear, +10 to-skill and +5 to-deadliness for 1d25+25 turns")
EFFECT(BERSERK_STR,    FALSE,  9,	"puts you in a berserker rage for d25+25 turns")
EFFECT(RESTORE_MANA,   FALSE,  20,	"restores your mana points to maximum")
EFFECT(RESTORE_EXP,    FALSE,  8,	"restores your experience")
EFFECT(INC_STR,        FALSE,  INHIBIT_POWER,	"restores and increases your strength up to a point")
EFFECT(INC_INT,        FALSE,  INHIBIT_POWER,	"restores and increases your intelligence up to a point")
EFFECT(INC_WIS,        FALSE,  INHIBIT_POWER,	"restores and increases your wisdom up to a point")
EFFECT(INC_DEX,        FALSE,  INHIBIT_POWER,	"restores and increases your dexterity up to a point")
EFFECT(INC_CON,        FALSE,  INHIBIT_POWER,	"restores and increases your constitution up to a point")
EFFECT(INC_CHR,        FALSE,  INHIBIT_POWER,	"restores and increases your charisma up to a point")
EFFECT(STAR_INC_STR,   FALSE,  INHIBIT_POWER,	"restores and increases your strength")
EFFECT(STAR_INC_INT,   FALSE,  INHIBIT_POWER,	"restores and increases your intelligence")
EFFECT(STAR_INC_WIS,   FALSE,  INHIBIT_POWER,	"restores and increases your wisdom")
EFFECT(STAR_INC_DEX,   FALSE,  INHIBIT_POWER,	"restores and increases your dexterity")
EFFECT(STAR_INC_CON,   FALSE,  INHIBIT_POWER,	"restores and increases your constitution")
EFFECT(STAR_INC_CHR,   FALSE,  INHIBIT_POWER,	"restores and increases your charisma")
EFFECT(AUGMENTATION,   FALSE,  INHIBIT_POWER,	"restores and increases all your stats")
EFFECT(ENLIGHTENMENT1, FALSE,  22,	"completely lights up and magically maps the level")
EFFECT(ENLIGHTENMENT2, FALSE,  INHIBIT_POWER,	"increases your intelligence and wisdom, detects and maps everything in the surrounding area, and identifies all items in your pack")
EFFECT(EXPERIENCE,     FALSE,  INHIBIT_POWER,	"grants half your current experience points, to a maximum of 100,000")
EFFECT(VAMPIRE,        FALSE,  5,	"changes you into a vampire, dealing 3d6 damage; holy and natural casters do not change and take 10d6 damage")
EFFECT(PHASE_DOOR,     FALSE,  5,	"teleports you randomly up to 10 squares away")
EFFECT(TELEPORT100,    FALSE,  6,	"teleports you randomly up to 100 squares away")
EFFECT(TELEPORT_LEVEL, FALSE,  15,	"teleports you one level up or down")
EFFECT(RECALL,         FALSE,  15,	"returns you to a recall point or takes you to a recall point after a short delay")
EFFECT(IDENTIFY,       FALSE,  9,	"reveals to you the extent of an item's magical powers")
EFFECT(REVEAL_CURSES,  FALSE,  15,	"reveals to you the extent of an item's magical powers and curses")
EFFECT(BRANDING,       FALSE,  20,	"brands a stack of missiles")
EFFECT(FRIGHTENING,    TRUE,   3,	"attempts to induce magical fear in a single monster")
EFFECT(REMOVE_CURSE,   FALSE,  10,	"attempts to remove curses from an item")
EFFECT(REM_CURSE_GOOD, FALSE,  15,	"makes multiple attempts to remove curses from an item")
EFFECT(ENCHANT_ARMOR1, FALSE,  12,	"attempts to magically enhance a piece of armour")
EFFECT(ENCHANT_ARMOR2, FALSE,  15,	"attempts to magically enhance a piece of armour with high chance of success")
EFFECT(ENCHANT_TO_HIT, FALSE,  20,	"attempts to magically enhance a weapon's to-skill bonus")
EFFECT(ENCHANT_TO_DAM, FALSE,  20,	"attempts to magically enhance a weapon's to-deadliness bonus")
EFFECT(ENCHANT_WEAPON, FALSE,  25,	"attempts to magically enhance a weapon both to-skill and to-deadliness")
EFFECT(RECHARGING1,    FALSE,  12,	"tries to recharge a wand or staff, destroying the wand or staff on failure")
EFFECT(RECHARGING2,    FALSE,  15,	"tries to recharge a wand or staff, destroying the wand or staff on failure")
EFFECT(LIGHT,          FALSE,  4,	"lights up an area and inflicts 2d8 damage on light-sensitive creatures")
EFFECT(MAPPING,        FALSE,  10,	"maps the area around you")
EFFECT(DETECT_GOLD,    FALSE,  3,	"detects gold and precious minerals nearby")
EFFECT(DETECT_ITEM,    FALSE,  6,	"detects objects nearby")
EFFECT(DETECT_TRAP,    FALSE,  6,	"detects traps nearby")
EFFECT(DETECT_DOOR,    FALSE,  6,	"detects doors and stairs nearby")
EFFECT(DETECT_INVIS,   FALSE,  6,	"detects invisible creatures nearby")
EFFECT(SATISFY_HUNGER, FALSE,  7,	"magically renders you well-fed")
EFFECT(BLESSING1,      FALSE,  6,	"increases your AC and to-hit bonus for 1d12+6 turns")
EFFECT(BLESSING2,      FALSE,  7,	"increases your AC and to-hit bonus for 1d24+12 turns")
EFFECT(BLESSING3,      FALSE,  8,	"increases your AC and to-hit bonus for 1d48+24 turns")
EFFECT(MONSTER_CONFU,  FALSE,  8,	"causes your next attack upon a monster to confuse it")
EFFECT(PROT_FROM_EVIL, FALSE,  6,	"grants you protection from evil for 1d25 plus 3 times your character level turns")
EFFECT(RUNE_PROTECT,   FALSE,  20,	"inscribes a glyph of warding beneath you, which monsters cannot move onto")
EFFECT(DOOR_DESTRUCT,  FALSE,  4,	"destroys adjacent doors")
EFFECT(DESTRUCTION,    FALSE,  20,	"destroys an area around you in the shape of a circle radius 15, and blinds you for 1d10+10 turns")
EFFECT(DISPEL_UNDEAD,  FALSE,  4,	"deals 60 damage to all undead creatures that you can see")
EFFECT(GENOCIDE,       FALSE,  20,	"removes all non-unique monsters represented by a chosen symbol from the level, dealing you damage in the process")
EFFECT(MASS_GENOCIDE,  FALSE,  25,	"removes all non-unique monsters within 20 squares, dealing you damage in the process")
EFFECT(ACQUIREMENT1,   FALSE,  INHIBIT_POWER,	"creates a good object nearby")
EFFECT(ACQUIREMENT2,   FALSE,  INHIBIT_POWER,	"creates a few good items nearby")
EFFECT(ELE_ATTACKS,    FALSE,  20,	"temporarily brands your weapon")
EFFECT(ACID_PROOF,     FALSE,  20,	"renders an item invulnerable to acid")
EFFECT(ELEC_PROOF,     FALSE,  20,	"renders an item invulnerable to electricity")
EFFECT(FIRE_PROOF,     FALSE,  20,	"renders an item invulnerable to fire")
EFFECT(COLD_PROOF,     FALSE,  20,	"renders an item invulnerable to cold")
EFFECT(STARLIGHT,      FALSE,  6,	"fires a line of light in all directions, each one hurting light-sensitive creatures (damage: 20 - 60+)")
EFFECT(DETECT_EVIL,    FALSE,  6,	"detects evil creatures nearby")
EFFECT(CURE_MEDIUM,    FALSE,  5,	"restores 10 - 30 hitpoints")
EFFECT(CURING,         FALSE,  9,	"heals cut damage, and cures all stunning, poison, blindness and confusion")
EFFECT(BANISHMENT,     FALSE,  20,	"teleports all evil monsters in your line of sight 80+ squares")
EFFECT(SLEEP_MONSTERS, FALSE,  8,	"tries to sleep all creatures within line of sight")
EFFECT(SLOW_MONSTERS,  FALSE,  7,	"tries to slow all monsters within line of sight")
EFFECT(SPEED2,         FALSE,  12,	"hastens you for 1d30+15 turns")
EFFECT(PROBING,        FALSE,  8,	"gives you information on the health and abilities of monsters you can see")
EFFECT(DISPEL_EVIL,    FALSE,  6,	"deals 60 damage to all evil creatures that you can see")
EFFECT(POWER,          FALSE,  10,	"deals 100 damage to all creatures that you can see")
EFFECT(HOLINESS,       FALSE,  12,	"inflicts damage on evil creatures you can see, cures 50 hit points, heals all temporary effects and grants you protection from evil (damage: 120)")
EFFECT(EARTHQUAKES,    FALSE,  5,	"causes an earthquake around you")
EFFECT(DETECTION,      FALSE,  8,	"detects treasure, traps, doors, stairs, and all creatures nearby")
EFFECT(MSTORM,         FALSE,  15,	"unleashes a blast of pure damage (125 - 200) around you")
EFFECT(STARBURST,      FALSE,  13,	"unleashes a blast of light (damage: 100 - 167) around you")
EFFECT(MASS_CONFU,     FALSE,  12,	"powerfully attempts to confuse all creatures within line of sight")
EFFECT(STARFIRE,       FALSE,  INHIBIT_POWER,	"fires several balls of confusing light (damage 30 - 90+ each) nearby")
EFFECT(WINDS,          FALSE,  INHIBIT_POWER,	"catches all nearby monsters in a whirlwind (damage: 100 - 200)")
EFFECT(HOLDING,     FALSE,  INHIBIT_POWER,	"attempts to put all undead in line of sight into stasis")
EFFECT(KELVAR,         FALSE,  INHIBIT_POWER,	"if any natural creatures are on the level, maps around them and detects all traps")
EFFECT(TELEPORT_AWAY2, TRUE,   12,	"teleports a target monster away (distance: 55-80)")
EFFECT(DISARMING,      TRUE,   6,	"destroys an adjacent trap, failure sets off the trap (success chance: 95%); adjacent doors are found and unlocked")
EFFECT(DOOR_DEST,      TRUE,   4,	"destroys an adjacent door")
EFFECT(STONE_TO_MUD,   TRUE,   6,	"turns rock into mud")
EFFECT(LIGHT,          TRUE,   6,	"lights up part of the dungeon in a straight line (damage: 4 - 20)")
EFFECT(SLEEP_MONSTER2, TRUE,   3,	"attempts to induce magical sleep in a single monster")
EFFECT(SLOW_MONSTER2,  TRUE,   3,	"attempts to magically slow a single monster")
EFFECT(CONFUSE_MONSTER, TRUE,  3,	"confuses a target monster")
EFFECT(FEAR_MONSTER,   TRUE,   3,	"attempts to induce magical fear in a single monster")
EFFECT(DRAIN_LIFE1,    TRUE,   10,	"drains life from a target creature (damage: 50 - 100)")
EFFECT(POLYMORPH,      TRUE,   7,	"polymorphs a monster into another kind of creature")
EFFECT(STINKING_CLOUD, TRUE,   3,	"fires a stinking cloud (damage: 12)")
EFFECT(MAGIC_MISSILE,  TRUE,   3,	"fires a magic missile (damage: 2 - 12)")
EFFECT(ACID_BOLT1,     TRUE,   4,	"creates an acid bolt (damage: 5 - 80)")
EFFECT(ELEC_BOLT1,     TRUE,   4,	"creates a lightning bolt (damage: 3 - 48)")
EFFECT(FIRE_BOLT1,     TRUE,   4,	"creates a fire bolt (damage: 6 - 98)")
EFFECT(COLD_BOLT1,     TRUE,   4,	"creates a frost bolt (damage: 4 - 64)")
EFFECT(ACID_BALL1,     TRUE,   9,	"creates an acid ball (damage: 60 - 90)")
EFFECT(ELEC_BALL1,     TRUE,   9,	"creates a lightning ball (damage: 40 - 70)")
EFFECT(FIRE_BALL1,     TRUE,   9,	"creates a fire ball (damage: 70 - 100)")
EFFECT(COLD_BALL1,     TRUE,   9,	"creates a frost ball (damage: 50 - 80)")
EFFECT(WONDER,         TRUE,   9,	"creates random and unpredictable effects")
EFFECT(DRAGON_FIRE,    TRUE,   15,	"creates an arc of fire (damage: 160)")
EFFECT(DRAGON_COLD,    TRUE,   15,	"creates an arc of cold (damage: 160)")
EFFECT(DRAGON_BREATH,  TRUE,   20,	"creates an arc of a random basic element or poison (damage: 180 - 210)")
EFFECT(ANNIHILATION,   TRUE,   12,	"drains life from a target creature (damage: 100 - 300)")
EFFECT(STRIKING,       TRUE,   15,	"fires a meteor (damage: 10 - 234)")
EFFECT(STORMS,         TRUE,   13,	"fires a bolt of storm lightning (damage: 35 - 140)")
EFFECT(SHARD_BOLT,     TRUE,   8,	"fires a bolt of shards (damage: 4 - 56)")
EFFECT(ILKORIN,        TRUE,   INHIBIT_POWER,	"fires a bolt of poison and then produces a large cloud of poison (damage ~30 - 310.  hurt 30.)")
EFFECT(BEGUILING,      TRUE,   INHIBIT_POWER,	"powerfully attempts to slow, confuse and sleep a target creature")
EFFECT(UNMAKING,       TRUE,   INHIBIT_POWER,	"creates various chaotic effects, some of them dangerous to the player")
EFFECT(OSSE,           TRUE,   INHIBIT_POWER,	"creates a massive tidal wave (damage: 3 * plev + d100)")
EFFECT(RESTORATION,    FALSE,  18,	"restores all your stats and your experience points")
EFFECT(TELEPORT_AWAY1, TRUE,   10,	"teleports a target monster away (distance: 45-60+)")
EFFECT(SLEEP_MONSTER1, TRUE,   3,	"attempts to induce magical sleep in a single monster")
EFFECT(SLOW_MONSTER1,  TRUE,   3,	"attempts to magically slow a single monster")
EFFECT(DRAIN_LIFE2,    TRUE,   8,	"drains life from a target creature (damage: 45 - 120)")
EFFECT(ACID_BOLT2,     TRUE,   5,	"creates an acid bolt (damage: 6 - 88)")
EFFECT(ELEC_BOLT2,     TRUE,   5,	"creates a lightning bolt (damage: 4 - 56)")
EFFECT(FIRE_BOLT2,     TRUE,   5,	"creates a fire bolt (damage: 7 - 104)")
EFFECT(COLD_BOLT2,     TRUE,   5,	"creates a frost bolt (damage: 5 - 72)")
EFFECT(ACID_BALL2,     TRUE,   10,	"creates an acid ball (damage: 60 - 100)")
EFFECT(ELEC_BALL2,     TRUE,   10,	"creates a lightning ball (damage: 40 - 80)")
EFFECT(FIRE_BALL2,     TRUE,   10,	"creates a fire ball (damage: 70 - 110)")
EFFECT(COLD_BALL2,     TRUE,   10,	"creates a frost ball (damage: 50 - 90)")
EFFECT(LIGHTINGSTRIKE, TRUE,   20,	"fires a powerful lightning bolt (damage: 18 - 272)")
EFFECT(NORTHWINDS,     TRUE,   20,	"creates a breath of cold north wind (damage: 21 - 296)")
EFFECT(DRAGONFIRE,     TRUE,   20,	"creates a powerful fire bolt (damage: 24 - 320)")
EFFECT(GLAURUNGS,      TRUE,   20,	"creates a sizzling bolt of acid (damage: 27 - 344)")
EFFECT(DELVING,        TRUE,   INHIBIT_POWER,	"creates a room if fired straight down, or else powerful stone to mud (damage 160 - 400)")
EFFECT(SHADOW,         FALSE,  INHIBIT_POWER,	"allows you to slip into the shadows")
EFFECT(AIR,            FALSE,  INHIBIT_POWER,	"bombards the area with multiple light, gravity and lightning balls")
EFFECT(PORTALS,        FALSE,  INHIBIT_POWER,	"allows directed teleportation")
EFFECT(GWINDOR,        FALSE,  0,	"illumination (2d15 damage)") 
EFFECT(DWARVES,        FALSE,  0,	"level clairvoyance")
EFFECT(ELESSAR,        FALSE,  0,	"heal (500) and restore life levels")
EFFECT(RAZORBACK,      FALSE,  0,	"Assume Dragonform; Activation in Dragonform: star ball (150)")
EFFECT(BLADETURNER,    FALSE,  0,	"Assume Dragonform; Activation in Dragonform: heroism, bless, and resistance")
EFFECT(SOULKEEPER,     FALSE,  0,	"heal (1000)")
EFFECT(ELEMENTS,       FALSE,  0,	"protection from the elements")
EFFECT(GIL_GALAD,      FALSE,  0,	"blinding light (75)")
EFFECT(NARGOTHROND,    FALSE,  0,	"heal (500)")
EFFECT(VALINOR,        FALSE,  0,	"resistance (20+d20 turns)")
EFFECT(HOLCOLLETH,     FALSE,  0,	"Sleep II")
EFFECT(THINGOL,        FALSE,  0,	"recharge magical device")
EFFECT(MAEGLIN,        TRUE,   0,	"mana bolt (9d8)")
EFFECT(PAURNIMMEN,     FALSE,  0,	"add cold damage to your melee attacks (50 turns)")
EFFECT(PAURNEN,        FALSE,  0,	"add acid damage to your melee attacks (30 turns)")
EFFECT(DAL,            FALSE,  0,	"remove fear and cure poison")
EFFECT(NARTHANC,       TRUE,   0,	"fire bolt (6d8)")
EFFECT(NIMTHANC,       TRUE,   0,	"frost bolt (5d8)")
EFFECT(DETHANC,        TRUE,   0,	"lightning bolt (4d8)")
EFFECT(RILIA,          TRUE,   0,	"stinking cloud (12)")
EFFECT(BELANGIL,       TRUE,   0,	"frost ball (3 * level / 2)")
EFFECT(ARANRUTH,       TRUE,   0,	"frost bolt (12d8)")
EFFECT(RINGIL,         TRUE,   0,	"frost cone (250)")
EFFECT(NARSIL,         TRUE,   0,	"fire ball (150)")
EFFECT(MANWE,          TRUE,   0,	"wide arc of force (300)")
EFFECT(AEGLOS,         TRUE,   0,	"frost ball (100)")
EFFECT(LOTHARANG,      FALSE,  0,	"cure wounds (4d12)")
EFFECT(ULMO,           TRUE,   0,	"teleport away (distance: 45-60+)")
EFFECT(AVAVIR,         FALSE,  0,	"word of recall")
EFFECT(TOTILA,         TRUE,   0,	"confuse monster")
EFFECT(FIRESTAR,       TRUE,   0,	"large fire ball (125)")
EFFECT(TURMIL,         TRUE,   0,	"drain life (90)")
EFFECT(DRAGON_BLACK,   FALSE,  9,	"assume dragon form; Activation in dragon form: breathe acid for 45-270 damage")
EFFECT(DRAGON_BLUE,    FALSE,  20,	"assume dragon form; Activation in dragon form: breathe lightning for 40-260 damage")
EFFECT(DRAGON_WHITE,   FALSE,  20,	"assume dragon form; Activation in dragon form: breathe frost for 45-270 damage")
EFFECT(DRAGON_RED,     FALSE,  20,	"assume dragon form; Activation in dragon form: breathe fire for 50-300 damage")
EFFECT(DRAGON_GREEN,   FALSE,  20,	"assume dragon form; Activation in dragon form: breathe poison gas for 45-270 damage")
EFFECT(DRAGON_MULTIHUED, FALSE,  20,	"assume dragon form; Activation in dragon form: breathe an element or poison for 60-360 damage")
EFFECT(DRAGON_SHINING, FALSE,  22,	"assume dragon form; Activation in dragon form: breathe light/darkness for 50-300 damage")
EFFECT(DRAGON_LAW,     FALSE,  22,	"assume dragon form; Activation in dragon form: breathe sound or shards for 60-360 damage")
EFFECT(DRAGON_BRONZE,  FALSE,  20,	"assume dragon form; Activation in dragon form: breathe confusionfor 40-260 damage")
EFFECT(DRAGON_GOLD,    FALSE,  20,	"assume dragon form; Activation in dragon form: breathe sound for 40-260 damage")
EFFECT(DRAGON_CHAOS,   FALSE,  22,	"assume dragon form; Activation in dragon form: breathe chaos or disenchantment for 55-330 damage")
EFFECT(DRAGON_BALANCE, FALSE,  23,	"assume dragon form; Activation in dragon form: breathe sound, shards, chaos, or disenchantment for 60-360 damage")
EFFECT(DRAGON_POWER,   FALSE,  25,	"assume dragon form; Activation in dragon form: breathe the elements for 75-450 damage")
EFFECT(RING_ACID,      TRUE,   11,	"cast an acid ball(80) and oppose acid")
EFFECT(RING_ELEC,      TRUE,   11,	"cast a cold ball(80) and oppose cold")
EFFECT(RING_FIRE,      TRUE,   11,	"cast a fire ball(80) and oppose fire")
EFFECT(RING_COLD,      TRUE,   11,	"cast an electricity ball(80) and oppose electricity")
EFFECT(RING_POIS,      TRUE,   11,	"cast a poison ball(80) and oppose poison")
EFFECT(AMULET_ESCAPING, FALSE,  10,	"teleport(40)")
EFFECT(AMULET_LION,    FALSE,  15,	"become lion")
EFFECT(AMULET_METAMORPH, FALSE,  15,	"Make a random shapechange")
EFFECT(RAND_FIRE1,         TRUE,   4,	"fire bolt (3 + level / 8)d8")
EFFECT(RAND_FIRE2,         TRUE,   5,	"sphere of fire (90)")
EFFECT(RAND_FIRE3,         FALSE,  6,	"fire storm (150)")
EFFECT(RAND_COLD1,         TRUE,   4,	"frost bolt (3 + level / 8)d8")
EFFECT(RAND_COLD2,         TRUE,   5,	"sphere of frost (90)")
EFFECT(RAND_COLD3,         FALSE,  6,	"frost storm (150)")
EFFECT(RAND_ACID1,         TRUE,   4,	"acid bolt (3 + level / 8)d8")
EFFECT(RAND_ACID2,         TRUE,   5,	"sphere of acid (90)")
EFFECT(RAND_ACID3,         FALSE,  6,	"acid storm (160)")
EFFECT(RAND_ELEC1,         TRUE,   4,	"electricity bolt (3 + level / 8)d8")
EFFECT(RAND_ELEC2,         TRUE,   5,	"ball lightning (100)")
EFFECT(RAND_ELEC3,         FALSE,  6,	"lightning strike (130+25)")
EFFECT(RAND_POIS1,         TRUE,   4,	"poison dart (3 + level / 10)d8")
EFFECT(RAND_POIS2,         TRUE,   5,	"poison cloud (110)")
EFFECT(RAND_LIGHT1,        TRUE,   6,	"blinding ball of light (50+10)")
EFFECT(RAND_LIGHT2,        FALSE,  6,	"dispel light-hating (175)")
EFFECT(RAND_DISPEL_UNDEAD, FALSE,  6,	"dispel undead (100)")
EFFECT(RAND_DISPEL_EVIL,   FALSE,  9,	"dispel evil (100)")
EFFECT(RAND_SMITE_UNDEAD,  TRUE,   8,	"dispel an undead (level / 4)d33")
EFFECT(RAND_SMITE_DEMON,   TRUE,   8,	"dispel a demon (level / 4)d33")
EFFECT(RAND_SMITE_DRAGON,  TRUE,   8,	"dispel a dragon (level / 4)d33")
EFFECT(RAND_HOLY_ORB,      TRUE,   5,	"holy orb (60)")
EFFECT(RAND_BLESS,         FALSE,  4,	"blessing (24+d24)")
EFFECT(RAND_FRIGHTEN_ALL,  FALSE,  5,	"frighten adversaries")
EFFECT(RAND_HEAL1,         FALSE,  5,	"heal (5d20)")
EFFECT(RAND_HEAL2,         FALSE,  8,	"heal (7d40)")
EFFECT(RAND_HEAL3,         FALSE,  10,	"heal (10d60)")
EFFECT(RAND_CURE,          FALSE,  8,	"cure ailments")
EFFECT(RAND_PROT_FROM_EVIL, FALSE,  6,	"protection from evil (24+d24)")
EFFECT(RAND_CHAOS,         TRUE,   9,	"chaos ball (d300)")
EFFECT(RAND_SHARD_SOUND,   TRUE,   9,	"shard or sound ball (150)")
EFFECT(RAND_NETHR,         TRUE,   8,	"nether orb (100)")
EFFECT(RAND_LINE_LIGHT,    TRUE,   4,	"ray of light (4d5)")
EFFECT(RAND_STARLIGHT,     FALSE,  5,	"starlight (4d5)")
EFFECT(RAND_EARTHQUAKE,    FALSE,  5,	"earthquake (radius 10)")
EFFECT(RAND_IDENTIFY,      FALSE,  6,	"identify")
EFFECT(RAND_SPEED,         FALSE,  10,	"haste self (20+d20)")
EFFECT(RAND_TELEPORT_AWAY, TRUE,   9,	"teleport away (distance: 45-60+)")
EFFECT(RAND_HEROISM,       FALSE,  6,	"heroism")
EFFECT(RAND_STORM_DANCE,   FALSE,  11,	"storm dance")
EFFECT(RAND_RESIST_ELEMENTS, FALSE,  8,	"resistance to the elements")
EFFECT(RAND_RESIST_ALL,    FALSE,  10,	"resistance")
EFFECT(RAND_TELEPORT1,     FALSE,  6,	"teleport self (30)")
EFFECT(RAND_TELEPORT2,     FALSE,  9,	"major displacement (200)")
EFFECT(RAND_RECALL,        FALSE,  10,	"recall")
EFFECT(RAND_REGAIN,        FALSE,  8,	"restore level")
EFFECT(RAND_RESTORE,       FALSE,  10,	"restore stats")
EFFECT(RAND_SHIELD,        FALSE,  8,	"magic shield")
EFFECT(RAND_BRAND_MISSILE, FALSE,  20,	"brand missiles")
EFFECT(RAND_SUPER_SHOOTING, FALSE,  10,	"an especially deadly shot")
EFFECT(RAND_DETECT_MONSTERS, FALSE,  4,	"detect monsters")
EFFECT(RAND_DETECT_EVIL,   FALSE,  3,	"detect evil")
EFFECT(RAND_DETECT_ALL,    FALSE,  8,	"detection")
EFFECT(RAND_MAGIC_MAP,     FALSE,  8,	"sense surroundings")
EFFECT(RAND_DETECT_D_S_T,  FALSE,  5,	"detect traps, doors, and stairs")
EFFECT(RAND_CONFU_FOE,     TRUE,   4,	"strong confuse monster")
EFFECT(RAND_SLEEP_FOE,     TRUE,   4,	"strong sleep monster")
EFFECT(RAND_TURN_FOE,      TRUE,   4,	"strong frighten monster")
EFFECT(RAND_SLOW_FOE,      TRUE,   4,	"strong slow monster")
EFFECT(RAND_BANISH_EVIL,   FALSE,  6,	"banish evil")
EFFECT(RAND_DISARM,        TRUE,   4,	"disarming")
EFFECT(RAND_CONFU_FOES,    FALSE,  5,	"confuse monsters")
EFFECT(RAND_SLEEP_FOES,    FALSE,  5,	"sleep monsters")
EFFECT(RAND_TURN_FOES,     FALSE,  5,	"frighten monsters")
EFFECT(RAND_SLOW_FOES,     FALSE,  5,	"slow monsters")
EFFECT(ACID_BLAST,     FALSE,  18,	"acid blast")
EFFECT(CHAIN_LIGHTNING, FALSE,  19,	"chain lightning")
EFFECT(LAVA_POOL,      FALSE,  22,	"lava pool")
EFFECT(ICE_WHIRLPOOL,  FALSE,  22,	"whirlpool of ice")
EFFECT(GROW_FOREST,    FALSE,  22,	"grow forest")
EFFECT(RESTORE_AND_ENHANCE, FALSE,  23,	"restore and enhance you")
EFFECT(ZONE_OF_CHAOS,  FALSE,  23,	"create a zone of chaos")
EFFECT(PRESSURE_WAVE,  FALSE,  21,	"pressure wave")
EFFECT(ENERGY_DRAIN,   FALSE,  25,	"drain energy")
EFFECT(MASS_STASIS,    FALSE,  20,	"mass stasis")
EFFECT(LIGHT_FROM_ABOVE, FALSE,  22,	"light from above")
EFFECT(MASS_POLYMORPH, FALSE,  18,	"mass polymorph")
EFFECT(GRAVITY_WAVE,   FALSE,  25,	"gravity wave")
EFFECT(ENLIST_EARTH,   TRUE,   20,	"summon allies from the Earth")
EFFECT(TELEPORT_ALL,   FALSE,  25,	"mass teleport")
EFFECT(BALROG_WHIP,    TRUE,   0,	"lash out at at range 2 for base weapon damage (unless target resists fire)")
EFFECT(MAGESTAFF,      FALSE,  0,	"restore 10 spell points (mages and necromancers)")
