/**
 * \file list-localities.h
 * \brief List of localities
 */
/* string			name */
LOC(HITHAEGLIR,		"Hithaeglir")
LOC(ERIADOR,		"Eriador")
LOC(ERED_LUIN,		"Ered Luin")
LOC(ERED_LUIN_SOUTH,"Ered Luin South")
LOC(OSSIRIAND,		"Ossiriand")
LOC(TAUR_IM_DUINATH,"Taur-Im-Duinath")
LOC(EAST_BELERIAND,	"East Beleriand")
LOC(ANDRAM,			"Andram")
LOC(WEST_BELERIAND,	"West Beleriand")
LOC(THARGELION,		"Thargelion")
LOC(DORIATH,		"Doriath")
LOC(HIMLAD,			"Himlad")
LOC(DOR_DINEN,		"Dor Dínen")
LOC(DORTHONION,		"Dorthonion")
LOC(TALATH_DIRNEN,	"Talath Dirnen")
LOC(BRETHIL,		"Brethil")
LOC(SIRION_VALE,	"Sirion Vale")
LOC(FEN_OF_SERECH,	"Fen of Serech")
LOC(ANFAUGLITH,		"Anfauglith")
LOC(LOTHLANN,		"Lothlann")
LOC(AMON_RUDH,		"Amon Rûdh")
LOC(NAN_DUNGORTHEB,	"Nan Dungortheb")
LOC(NARGOTHROND,	"Nargothrond")
LOC(TOL_IN_GAURHOTH,"Tol-In-Gaurhoth")
LOC(ANGBAND,		"Angband")
LOC(ANDUIN_VALE,	"Anduin Vale")
LOC(GLADDEN_FIELDS,	"Gladden Fields")
LOC(KHAZAD_DUM,		"Khazad Dûm")
LOC(BELEGOST,		"Belegost")
LOC(MENEGROTH,		"Menegroth")
LOC(EPHEL_BRANDIR,	"Ephel Brandir")
LOC(GONDOLIN,		"Gondolin")
LOC(ENT_PATH,		"Ent Path")
LOC(ERIADOR_SOUTH,	"Eriador South")
LOC(UNDERWORLD,		"Underworld")
LOC(MOUNTAIN_TOP,	"Mountain Top")
LOC(ARENA,			"Arena")
