/*
 * File: options.c
 * Purpose: Options table and definitions.
 *
 * Copyright (c) 1997 Ben Harrison
 *
 * This work is free software; you can redistribute it and/or modify it
 * under the terms of either:
 *
 * a) the GNU General Public License as published by the Free Software
 *    Foundation, version 2, or
 *
 * b) the "Angband licence":
 *    This software may be copied and distributed for educational, research,
 *    and not for profit purposes provided that this copyright and statement
 *    are included in all such copies.  Other copyrights may also apply.
 */
#include "angband.h"
#include "option.h"

/**
 * Option screen interface
 */
const int option_page[OPT_PAGE_MAX][OPT_PAGE_PER] =
  {
    /*** User-Interface ***/
    
    {
      OPT_rogue_like_commands,
      OPT_quick_messages,
      OPT_floor_query_flag,
      OPT_carry_query_flag,
      OPT_use_old_target,
      OPT_show_labels,
      OPT_show_weights,
      OPT_show_choices,
      OPT_show_details,
      OPT_show_lists,
      OPT_show_flavors,
      OPT_show_detect,
      OPT_show_menus,
      OPT_hp_changes_colour,
      OPT_mouse_buttons,
      OPT_bottom_status,
      OPT_squelch_worthless,
      OPT_hide_squelchable,
      OPT_xchars_to_file,
      OPT_use_sound
    },

    /*** Disturbance ***/
    
    {
      OPT_run_ignore_stairs,
      OPT_run_ignore_doors,
      OPT_run_cut_corners,
      OPT_run_use_corners,
      OPT_disturb_move,
      OPT_disturb_near,
      OPT_disturb_panel,
      OPT_disturb_trap_detect,
      OPT_disturb_state,
      OPT_disturb_minor,
      OPT_disturb_other,
      OPT_alert_hitpoint,
      OPT_verify_destroy,
      OPT_verify_destroy_junk,
      OPT_verify_special,
      OPT_ring_bell,
      OPT_auto_more,
      OPT_easy_more,
      OPT_NONE,
      OPT_NONE
    },
    
    /*** Game-Play ***/
    
    {
      OPT_auto_scum,
      OPT_easy_open,
      OPT_easy_disarm,
      OPT_expand_look,
      OPT_expand_list,
      OPT_view_perma_grids,
      OPT_view_torch_grids,
      OPT_dungeon_stair,
      OPT_stack_force_notes,
      OPT_stack_force_costs,
      OPT_always_pickup,
      OPT_pickup_inven,
      OPT_always_repeat,
      OPT_smart_cheat,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE
    },
    
    /*** Efficiency and Lighting ***/
    
    {
      OPT_view_reduce_lite,
      OPT_hidden_player,
      OPT_avoid_abort,
      OPT_avoid_other,
      OPT_flush_failure,
      OPT_flush_disturb,
      OPT_fresh_before,
      OPT_fresh_after,
      OPT_compress_savefile,
      OPT_hilite_player,
      OPT_view_yellow_lite,
      OPT_view_bright_lite,
      OPT_view_granite_lite,
      OPT_view_special_lite,
      OPT_center_player,
      OPT_center_running,
      OPT_show_piles,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE
    },
    
    /*** Birth ***/
    
    {
      OPT_birth_ironman, 
      OPT_birth_thrall,	      
      OPT_birth_small_device,
      OPT_birth_dungeon,
      OPT_birth_no_sell,
      OPT_birth_no_artifacts,
      255,
      255,
      255,
      255,
      255,
      255,
      255,
      255,
      255,
      255,
      255,
      255,
      255,
      255
    },
    
     /*** Cheat ***/
    
    {
      OPT_cheat_peek,
      OPT_cheat_hear,
      OPT_cheat_room,
      OPT_cheat_xtra,
      OPT_cheat_know,
      OPT_cheat_live,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE,
      OPT_NONE
    }
  };


typedef struct
{
	const char *name;
	const char *description;
	bool normal;
} option_entry;

static option_entry options[OPT_MAX] =
{
  {"rogue_like_commands",   "Rogue-like commands",
   FALSE /*  */},
  {"quick_messages",        "Activate quick messages",
   TRUE /*  */},
  {"floor_query_flag",      "Prompt for floor item selection",
   TRUE /*  */},
  {"carry_query_flag",      "Prompt before picking things up",
   FALSE /*  */},
  {"use_old_target",        "Use old target by default",
   FALSE /*  */},
  {"always_pickup",         "Pick things up by default",
   TRUE /*  */},
  {"always_repeat",         "Repeat obvious commands",
   TRUE /*  */},
  {"squelch_worthless",     "Squelch worthless items automatically",
   FALSE /*  */},
  {"stack_force_notes",     "Merge inscriptions when stacking",
   TRUE /*  */},
  {"stack_force_costs",     "Merge discounts when stacking",
   FALSE /*  */},
  {"show_labels",           "Show labels in equipment listings",
   TRUE /*  */},
  {"show_weights",          "Show weights in all object listings",
   TRUE /*  */},
  {"show_choices",          "Show choices in inven/equip windows",
   TRUE /*  */},
  {"show_details",          "Show details in monster descriptions",
   TRUE /*  */},
  {"use_metric",            "Use metric (SI) measurements",
   FALSE /*  */},
  {"show_flavors",          "Show flavors in object descriptions",
   TRUE /*  */},
  {"run_ignore_stairs",     "When running, ignore stairs",
   TRUE /*  */},
  {"run_ignore_doors",	     "When running, ignore doors",
   TRUE /*  */},
  {"run_cut_corners",       "When running, cut corners",
   TRUE /*  */},
  {"run_use_corners",       "When running, use corners",
   TRUE /*  */},
  {"disturb_move",          "Disturb whenever any monster moves",
   TRUE /*  */},
  {"disturb_near",          "Disturb whenever viewable monster moves",
   TRUE /*  */},
  {"disturb_panel",         "Disturb whenever map panel changes",
   TRUE /*  */},
  {"disturb_state",         "Disturb whenever player state changes",
   TRUE /*  */},
  {"disturb_minor",         "Disturb whenever boring things happen",
   TRUE /*  */},
  {"disturb_other",         "Disturb whenever various things happen",
   FALSE /*  */},
  {"alert_hitpoint",        "Alert user to critical hitpoints",
   TRUE /*  */},
  {"alert_failure",         "Alert user to various failures",
   FALSE /*  */},
  {"verify_destroy",        "Verify destruction of objects",
   TRUE /*  */},
  {"verify_special",        "Verify use of special commands",
   TRUE /*  */},
  {"ring_bell",             "Audible bell (on errors, etc)",
   TRUE /*  */},
  {"verify_destroy_junk",   "Verify destruction of worthless objects",
   TRUE /*  */},
  {"pickup_inven",          "Always pickup items matching inventory",
   TRUE /*  */},
  {"auto_scum",             "Auto-scum for good levels",
   FALSE /*  */},
  {"easy_open",             "Open and close doors automatically",
   TRUE /*  */},
  {"easy_disarm",           "Disarm traps automatically",
   FALSE /*  */},
  {"expand_look",           "Expand the power of the look command",
   TRUE /*  */},
  {"expand_list",           "Expand the power of the list commands",
   FALSE /*  */},
  {"view_perma_grids",      "Map remembers all perma-lit grids",
   TRUE /*  */},
  {"view_torch_grids",      "Map remembers all torch-lit grids",
   TRUE /*  */},
  {"auto_more",             "Automatically clear '-more-' prompts",
   FALSE /*  */},
  {"dungeon_stair",         "Generate dungeons with connected stairs",
   TRUE /*  */},
  {"strong_squelch",        "Auto-squelched items are immediately destroyed",
   FALSE /*  */},
  {"bottom_status",         "Status is shown at the bottom of the screen",
   FALSE /*  */},
  {"mouse_buttons",         "Mouse commands are enabled",
   TRUE /*  */},
  {"show_menus",            "Enter key brings up command menu",
   TRUE /*  */},
  {"xchars_to_file",        "Allow accents in output files",
   FALSE /*  */},
  {"smart_cheat",           "Monsters exploit players weaknesses",
   FALSE /*  */},
  {"view_reduce_lite",	     "Reduce light radius when running",
   FALSE /*  */},
  {"hidden_player",         "Hide player symbol when running",
   FALSE /*  */},
  {"avoid_abort",           "Avoid checking for user abort",
   FALSE /*  */},
  {"avoid_other",           "Avoid processing special colors",
   FALSE /*  */},
  {"flush_failure",         "Flush input on various failures",
   TRUE /*  */},
  {"flush_disturb",         "Flush input whenever disturbed",
   FALSE /*  */},
  {"center_player",         "Keep the player centered (slow)",
   FALSE /*  */},
  {"fresh_before",          "Flush output before every command",
   TRUE /*  */},
  {"fresh_after",           "Flush output after various things",
   FALSE /*  */},
  {"center_running",        "Keep player centered while running (slow)",
   FALSE /*  */},
  {"compress_savefile",     "Compress messages in savefiles",
   FALSE /*  */},
  {"hilite_player",         "Highlight the player with the cursor",
   FALSE /*  */},
  {"view_yellow_lite",      "Use special colors for torch lite",
   FALSE /*  */},
  {"view_bright_lite",	     "Use special colors for field of view",
   TRUE /*  */},
  {"view_granite_lite",     "Use special colors for wall grids",
   FALSE /*  */},
  {"view_special_lite",     "Use special colors for floor grids",
   TRUE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {"easy_more",             "Minimise '-more-' prompts",
   FALSE /*  */},
  {NULL,                     NULL,		
   FALSE /*  */},
  {"show_piles",            "Show stacks using special attr/char",
   FALSE /*  */},
  {"hp_changes_colour",     "Player colour indicates low hit points",
   TRUE /*  */},
  {"show_detect",           "Show detection region",
   TRUE /*  */},
  {"disturb_trap_detect",   "Disturb when leaving last trap detect area",
   TRUE /*  */},
  {"show_lists",            "Automatically show lists for commands",
   TRUE /*  */},
  {"hide_squelchable",      "Hide items set as squelchable",
   TRUE /*  */},
  {"auto_squelch",          "Destroy items marked as squelch automatically",
   FALSE /*  */},
  {"use_sound",             "Play sounds in game",
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {"birth_point_based",     "Birth: Use point based character generation",
   TRUE /*  */},
  {"birth_auto_roller",     "Birth: Use Autoroller if rolling for stats",
   FALSE /*  */},
  {"birth_take_notes",      "Birth: Have notes written to a file",
   TRUE /*  */},
  {"birth_preserve",        "Birth: No special feelings/artifacts preserved",
   TRUE /*  */},
  {"birth_no_sell",         "Birth: No selling to stores",
   FALSE /*  */},
  {"birth_ironman",         "Birth: Never return to less danger",
   FALSE /*  */},
  {"birth_thrall",          "Birth: Start as a thrall at the gate of Angband",
   FALSE /*  */},
  {"birth_small_device",    "Birth: View and spell distances halved",
   FALSE /*  */},
  {"birth_dungeon",         "Birth: Play with no wilderness",
   FALSE /*  */},
  {"birth_no_artifacts",    "Birth: Restrict creation of artifacts",
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,		
   FALSE /*  */},
  {NULL,                     NULL,		
   FALSE /*  */},
  {NULL,                     NULL,		
   FALSE /*  */},
  {NULL,                     NULL,		
   FALSE /*  */},
  {"cheat_peak",            "Cheat: Peek into object creation",
   FALSE /*  */},
  {"cheat_hear",            "Cheat: Peek into monster creation",
   FALSE /*  */},
  {"cheat_room",            "Cheat: Peek into dungeon creation",
   FALSE /*  */},
  {"cheat_xtra",            "Cheat: Peek into something else",
   FALSE /*  */},
  {"cheat_know",            "Cheat: Know complete monster info",
   FALSE /*  */},
  {"cheat_live",            "Cheat: Allow player to avoid death",
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {"adult_point_based",     "Adult: Use point based character generation",
   TRUE /*  */},
  {"adult_auto_roller",     "Adult: Use Autoroller if rolling for stats",
   TRUE /*  */},
  {"adult_take_notes",      "Adult: Have notes written to a file",
   TRUE /*  */},
  {"adult_preserve",        "Adult: Artifacts preserved, no special feelings",
   TRUE /*  */},
  {"adult_no_sell",         "Adult: No selling to stores",
   FALSE /*  */},
  {"adult_ironman",         "Adult: Never return to less danger",
   FALSE /*  */},
  {"adult_thrall",          "Adult: Start as a thrall at the gate of Angband",
   FALSE /*  */},
  {"adult_small_device",    "Adult: View and spell distances halved",
   FALSE /*  */},
  {"adult_dungeon",         "Adult: Play with no wilderness",
   FALSE /*  */},
  {"adult_no_artifacts",    "Adult: Restrict creation of artifacts",
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,	
   FALSE /*  */},
  {NULL,                     NULL,	
   FALSE /*  */},
  {NULL,                     NULL,	
   FALSE /*  */},
  {"score_peek",            "Score: Peek into object creation",
   FALSE /*  */},
  {"score_hear",            "Score: Peek into monster creation",
   FALSE /*  */},
  {"score_room",            "Score: Peek into dungeon creation",
   FALSE /*  */},
  {"score_xtra",            "Score: Peek into something else",
   FALSE /*  */},
  {"score_know",            "Score: Know complete monster info",
   FALSE /*  */},
  {"score_live",            "Score: Allow player to avoid death",
   FALSE /*  */},
  {NULL,                     NULL,	
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */},
  {NULL,                     NULL,
   FALSE /*  */}
};


/* Accessor functions */
const char *option_name(int opt)
{
	if (opt >= OPT_MAX) return NULL;
	return options[opt].name;
}

const char *option_desc(int opt)
{
	if (opt >= OPT_MAX) return NULL;
	return options[opt].description;
}

/* Setup functions */
bool option_set(const char *name, bool on)
{
	size_t opt;
	for (opt = 0; opt < OPT_ADULT; opt++)
	{
		if (!options[opt].name || !streq(options[opt].name, name))
			continue;

		op_ptr->opt[opt] = on;
		if (on && opt > OPT_CHEAT && opt < OPT_ADULT)
			op_ptr->opt[opt + (OPT_SCORE - OPT_CHEAT)] = TRUE;

		return TRUE;
	}

	return FALSE;
}

void option_set_defaults(void)
{
	size_t opt;
	for (opt = 0; opt < OPT_MAX; opt++)
		op_ptr->opt[opt] = options[opt].normal;
}
