char *release_notes="FAAngband NDS version 2.50  (2008-12-10 22:02)\n"
"\n"
"L quick    = toggle keyboard\n"
"L hold     = direction pad overlay\n"
"L + key    = shifted key\n"
"L + dirpad = run\n"
"\n"
"R = toggle zoom\n"
"\n"
"Default key bindings (can be changed):\n"
"\n"
"  X = Esc\n"
"  A = Return / accept\n"
"  B = attack nearest / rest\n"
"  Y = 'y' (yes)\n"
"\n"
"Automatic options: auto_more, Term-1=messages\n"
"Suggested options: center_player\n"
"\n"
"L long hold to redefine all key bindings\n"
"";