MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = abilattr.txt angdesc.txt basctask.txt birth.hlp cmddesc.txt cmdlist.txt combat.hlp combat.txt command.hlp defence.txt equip.txt explore.hlp fadesc.txt general.hlp getinfo.txt help.hlp keymap.txt magic.txt mapmode.txt newbie.txt oangdesc.txt objs-mon.txt optdesc.txt raceclas.txt specialt.txt symbols.txt terminal.txt town.txt wild-dun.txt
PACKAGE = help

