MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = flvr-dvg.prf  font-nds.prf  graf-ibm.prf  graf-xxx.prf  pref-win.prf \
       flvr-new.prf  font.prf      graf-lsl.prf  message.prf   pref-x11.prf \
       flvr-xxx.prf  font-sdl.prf  graf-mac.prf  pref-acn.prf  shades.prf \
       font-ami.prf  font-win.prf  graf-nds.prf  pref-ami.prf  user-mac.prf \
       font-dos.prf  font-x11.prf  graf-new.prf  pref-emx.prf  user.prf \
       font-ext.prf  font-xxx.prf  graf.prf      pref-gcu.prf  xtra-dvg.prf \
       font-gtk.prf  graf-ami.prf  graf-sdl.prf  pref-mac.prf  xtra-new.prf \
       font-ibm.prf  graf-dvg.prf  graf-win.prf  pref.prf      xtra-xxx.prf \
       font-mac.prf  graf-gcu.prf  graf-x11.prf  pref-sdl.prf  font-gcu.prf

PACKAGE = pref

