MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = flvr-dvg.prf  font.prf    message.prf   user.prf \
       flvr-new.prf  font-sdl.prf  graf-new.prf  xtra-dvg.prf \
       flvr-xxx.prf  font-win.prf  graf.prf      xtra-new.prf \
       font-ext.prf  font-x11.prf  pref.prf      xtra-xxx.prf \
       font-gcu.prf  font-xxx.prf  \
       graf-dvg.prf  graf-shb.prf  xtra-shb.prf flvr-shb.prf \
       font-mac.prf  graf-xxx.prf  graf-nmd.prf \
       font-nds.prf  flvr-nmd.prf  xtra-nmd.prf \

PACKAGE = pref

