MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = flvr-dvg.prf  font.prf      graf-nds.prf  message.prf   user.prf \
       flvr-new.prf  font-sdl.prf  graf-new.prf  pref-gcu.prf  xtra-dvg.prf \
       flvr-xxx.prf  font-win.prf  graf.prf      pref-mac.prf  xtra-new.prf \
       font-ext.prf  font-x11.prf  graf-sdl.prf  pref.prf      xtra-xxx.prf \
       font-gcu.prf  font-xxx.prf  graf-win.prf  pref-sdl.prf  user.prf \
       font-gtk.prf  graf-dvg.prf  graf-x11.prf  pref-win.prf  \
       font-mac.prf  graf-gcu.prf  graf-xxx.prf  pref-x11.prf graf-nmd.prf \
       font-nds.prf  graf-mac.prf  user-mac.prf  flvr-nmd.prf xtra-nmd.prf \

PACKAGE = pref

