MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = a_cursed.txt a_normal.txt boat_s.txt boat.txt bravado.txt dead_s.txt dead.txt names.txt news_s.txt news.txt splash_s.txt splash.txt tree_s.txt tree.txt w_cursed.txt w_normal.txt
PACKAGE = file

